### ISSUE TITLE
Unable to compile:   Only YAML (.yaml / .yml) files are supported.

### ISSUE THREAD

**Issue by mihsu81** [nirnachmani/ESP32-S3-Box-3-Firmware#8]
Hi @nirnachmani,
Thanks for your great work combining all these features.
I'm getting the below error when trying to compile using your package.
Any ideea what could be wrong?

```
INFO ESPHome 2024.7.2
INFO Reading configuration /config/esphome/esp32-s3-box-3-5ac364.yaml...
Failed config

packages: [source /config/esphome/esp32-s3-box-3-5ac364.yaml:21]
  
  Only YAML (.yaml / .yml) files are supported.
  esphome.voice-assistant: |-
    github://nirnachmani/esp32-s3-box-3-firmware/esp32-s3-box-3-firmware-cc+sensors+media_player.yaml@main
```

Here's the full config file:
```yaml
substitutions:
  name: esp32-s3-box-3-5ac364
  devicename: esp32_s3_box_3_5ac364
  friendly_name: ESP32 S3 Box 3 5ac364
  micro_wake_word_model: hey_jarvis
  wake_word_text: "Hey Jarvis"
  starting_up: "Pornire..."
  wake_word_prompt: "Spune \\\"Hey Jarvis\\\""
  listening_prompt: "Cum te pot ajuta?"
  error_prompt: "Scuze. A fost intâmpinată o eroare."

external_components:
  - source: github://pr#5230
    components: esp_adf
    refresh: 0s

packages:
  esphome.voice-assistant: github://nirnachmani/esp32-s3-box-3-firmware/esp32-s3-box-3-firmware-cc+sensors+media_player.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  reboot_timeout: 1h
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 20.5
  enable_btm: true
  enable_rrm: true
  ap:
    ssid: "${friendly_name} Fallback"

captive_portal:

ota:
  - platform: esphome
    password: !secret ota_password

safe_mode:
  disabled: false

web_server:
  port: 80
  auth:
    username: !secret username
    password: !secret password
  include_internal: true

time:
  - platform: homeassistant
    id: homeassistant_time

mdns:
  disabled: false

binary_sensor:
  - platform: status
    name: Status

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    dns_address:
      name: DNS Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: MAC Wifi Address

  - platform: version
    name: ESPHome Version

button:
  - platform: restart
    name: Restart
    id: ${devicename}_restart
    entity_category: diagnostic

  - platform: factory_reset
    name: Factory Reset
    id: ${devicename}_fatory_reset
    internal: true
    entity_category: diagnostic

  - platform: safe_mode
    name: Safe Mode Boot
    id: ${devicename}_safe_mode_boot
    entity_category: diagnostic

sensor:
  - platform: uptime
    name: Device Uptime
    id: ${devicename}_device_uptime

  - platform: wifi_signal
    name: Wifi Signal
    id: ${devicename}_wifi_signal
    update_interval: 60s

  - platform: internal_temperature
    name: Internal Temperature
    id: ${devicename}_internal_temperature
    update_interval: 60s

  - platform: template
    name: Free Memory
    icon: mdi:memory
    entity_category: diagnostic
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
```
