### ISSUE TITLE
on wake word beep

### ISSUE THREAD

**Issue by ecto1a2003** [nirnachmani/ESP32-S3-Box-3-Firmware#9]
I've written some extra code to add a beep when wake word is detected. do you want to review it and possibly add it?

**Comment by nirnachmani** [comment]
Sure! thank you. Any chance that you added a switch that allows the user to enable to disable the beep?

**Comment by ecto1a2003** [comment]
Im not that experienced. Also hardcoded the sound path. Ao that should probably be worked into a easy to substitute setting . Ill get it uploaded tomorrow

**Comment by ecto1a2003** [comment]
just getting back to this, what are you using for your timer noise
?

**Comment by nirnachmani** [comment]
I use a local fie, found it on the internet. If I remember correctly I was not able to play online sound files on the adf_media_player.

```
  on_timer_finished:
    - script.execute: stop_voice_assistant
    - lambda: id(voice_assistant_phase) = ${voice_assist_timer_finished_phase_id};
    - switch.turn_on: timer_ringing
    - script.execute: draw_display
    - wait_until:
        not:
          microphone.is_capturing:
    - while:
        condition:
          switch.is_on: timer_ringing
        then:
          - media_player.play_media:
              id: adf_media_player
              media_url: 'http://192.168.1.32:8123/local/voice-assistant_sounds_timer_finished.mp3'          
          - delay: 1s
    - wait_until:
        not:
          media_player.is_playing:
    - switch.turn_off: timer_ringing
    - media_player.stop
    - script.execute: return_to_idle    
```
